# 🔢 NumPy Mastery: Complete Guide
### From Fundamentals to Machine Learning Applications

---

**Author:** Tuvya Algotar  
**Institution:** NMIMS Navi Mumbai | B.Tech AI & Data Science (First Year)  
**Date:** March 2026  
**Learning Goal:** Learn NumPy for Data Science & Machine Learning  
**Time Invested:** 3+ hours  

---

## 📚 Table of Contents

1. [Introduction & Setup](#introduction)
2. [Array Creation Methods](#creation)
3. [Array Operations & Broadcasting](#operations)
4. [Indexing & Slicing](#indexing)
5. [2D Arrays & Matrix Operations](#matrices)
6. [Mathematical Functions](#math)
7. [Boolean Indexing & Filtering](#boolean)
8. [Real-World Applications](#applications)

---

> **💡 Key Insight:** NumPy is 10-50x faster than Python lists because it uses optimized C code and stores data in contiguous memory blocks.

---

In [141]:
# ========================================
# SETUP & IMPORTS
# ========================================

import numpy as np
import sys

print("NumPy Version:", np.__version__)
print("Python Version:", sys.version)
print("\n" + "="*50)
print("NumPy Setup Complete! ✓")
print("="*50)

NumPy Version: 2.3.5
Python Version: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]

NumPy Setup Complete! ✓


---

## 1️⃣ Array Creation Methods <a id="creation"></a>
---

## Basic Array Creation

In [142]:
# ========================================
# METHOD 1: From Python List
# ========================================
print("\n"+"-"*50+"\n")

list1 = [1,2,3,4,5]
arr1 = np.array(list1)
print("Basic information about array: \n")
print(f"Shape of array: {arr1.shape}")
print(f"Type of data in array: {arr1.dtype}")
print(f"Dimension of array: {arr1.ndim}")
print(f"Size of array (total elements): {arr1.size}")
print("\n"+"-"*50+"\n")


--------------------------------------------------

Basic information about array: 

Shape of array: (5,)
Type of data in array: int64
Dimension of array: 1
Size of array (total elements): 5

--------------------------------------------------



In [143]:
# ========================================
# METHOD 2: Directly from Values
# ========================================
print("\n"+"-"*50+"\n")

arr2 = np.array([10,20,30,40,50,60])
print("Direct arrays created using Numpy: ",arr2)

arr3 = np.array([1.3,5.6,8.3],dtype=np.float32)
print("Float arrays: ",arr3)
print("Data type of float array: ",arr3.dtype)

print("\n"+"-"*50+"\n")


--------------------------------------------------

Direct arrays created using Numpy:  [10 20 30 40 50 60]
Float arrays:  [1.3 5.6 8.3]
Data type of float array:  float32

--------------------------------------------------



In [144]:
# ========================================
# ZEROS & ONES
# ========================================

print("\n"+"-"*50+"\n")

zeros = np.zeros(10)
print(f"1-D Matrix of zeros: {zeros}")
print("\n")
zeros_2d = np.zeros((3,4))
print(f"2-D Matrix of zeros: {zeros_2d}")
print("\n"+"-"*50+"\n")

ones = np.ones(5)
print("1-d matrix of ones:",ones)
print("\n")
ones_2d = np.ones((2,3))
print("2-d matrix of ones:",ones_2d)

print("\n"+"-"*50+"\n")


--------------------------------------------------

1-D Matrix of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2-D Matrix of zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

--------------------------------------------------

1-d matrix of ones: [1. 1. 1. 1. 1.]


2-d matrix of ones: [[1. 1. 1.]
 [1. 1. 1.]]

--------------------------------------------------



In [145]:

# ========================================
# RANGE ARRAYS
# ========================================

print("\n"+"-"*50+"\n")

even_no = np.arange(0,41,2)
print("Even numbers till 41:\n",even_no)

print("\n"+"-"*50+"\n")

linear = np.linspace(0,11,10)
print("linespace(0,11,10):\n",linear)

print("\n"+"-"*50+"\n")


--------------------------------------------------

Even numbers till 41:
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]

--------------------------------------------------

linespace(0,11,10):
 [ 0.          1.22222222  2.44444444  3.66666667  4.88888889  6.11111111
  7.33333333  8.55555556  9.77777778 11.        ]

--------------------------------------------------



In [146]:

# ========================================
# IDENTITY MATRIX
# ========================================

print("\n"+"-"*50+"\n")

identity = np.eye(3)
print("\nIdentity Matrix:\n",identity)

print("\n"+"-"*50+"\n")


--------------------------------------------------


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--------------------------------------------------



In [147]:
# ========================================
# RANDOM ARRAYS
# ========================================

print("\n"+"-"*50+"\n")

#Random values between 0-1
random = np.random.rand(3)
print("random arrays between 0 to 1:\n",random)

print("\n"+"-"*50+"\n")

#Random integars
random_int = np.random.randint(1,50,size=6)
print("random integers:\n",random_int)

print("\n"+"-"*50+"\n")


--------------------------------------------------

random arrays between 0 to 1:
 [0.05232347 0.97784637 0.29555673]

--------------------------------------------------

random integers:
 [19 40 41 29 23 37]

--------------------------------------------------



---

## 2️⃣ Array Operations & Broadcasting <a id="operations"></a>

NumPy's **vectorization** means operations apply to entire arrays at once (no loops!).  
**Broadcasting** allows operations on arrays of different shapes.

---

In [148]:
# ========================================
# ARITHMETIC OPERATIONS (Element-wise)
# ========================================

arr = np.array([10,20,30,40,50])
print("Original array:",arr)
add = arr+5
print("Adding 5 to matrix:",add)
sub = arr-10
print("Subtracting 10 from every element:",sub)
mul = arr*2
print("Multiplying every element by 2:",mul)
div = arr/10
print("Divide every element by 10:",div)
square = arr**2
print("Squaring every element (power of 2):",square)
print("-"*50)

Original array: [10 20 30 40 50]
Adding 5 to matrix: [15 25 35 45 55]
Subtracting 10 from every element: [ 0 10 20 30 40]
Multiplying every element by 2: [ 20  40  60  80 100]
Divide every element by 10: [1. 2. 3. 4. 5.]
Squaring every element (power of 2): [ 100  400  900 1600 2500]
--------------------------------------------------


In [149]:
# ARRAY TO ARRAY OPERATIONS

arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
add = arr1+arr2
print("Adding both matrix:",add)
mul = arr1*arr2
print("Multipying both matrix:",mul)

Adding both matrix: [11 22 33]
Multipying both matrix: [10 40 90]


In [150]:
# BROADCASTING EXAMPLES
print("\n"+"-"*50+"\n")
arr = np.array([1,2,3])
broadcast1 = arr + 10
print("Adding 10 in arr:\n",broadcast1)
print("\n"+"-"*50)

# 2D + 1D
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
arr3 = arr1+arr2
print("2D+1D:\n",arr3)
print("\n"+"-"*50)


--------------------------------------------------

Adding 10 in arr:
 [11 12 13]

--------------------------------------------------
2D+1D:
 [[11 22 33]
 [14 25 36]]

--------------------------------------------------


## Indexing and Slicing
- **Indexing**
- **Slicing**

In [151]:

arr = np.array([1,2,3,4])
print("First 3:",arr[0:3])
print("Last 3:",arr[-3:])
print("Every 2nd:",arr[::2])
print("Reverse Array:",arr[::-1])
print("With exculsive indexing:",arr[2:4])

First 3: [1 2 3]
Last 3: [2 3 4]
Every 2nd: [1 3]
Reverse Array: [4 3 2 1]
With exculsive indexing: [3 4]


## 2D Arrays & Matrix Operations

- Why 2D arrays matter for ML
- Examples: images, datasets, neural networks

In [152]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("\n3x3 Matrix:\n",arr)
print("\nShape of matrix:",arr.shape)
print("Dimensions of matrix:",arr.ndim)
print("Total elements in matrix:",arr.size)
print("\n")
arr1D = np.array([1,2,3,4,5,6,7,8,9])
print("Reshaping to 2D:\n",arr1D.reshape(3,3))


3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of matrix: (3, 3)
Dimensions of matrix: 2
Total elements in matrix: 9


Reshaping to 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [153]:
arr2D = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
print("\nFirst row:",arr2D[0,:])
print("\nSecond row:",arr2D[1,:])
print("\nThird row:",arr2D[2,:])
print("\nFirst coloum:",arr2D[:,0])
print("\nSecomd coloum:",arr2D[:,1])
print("\nThird coloum:",arr2D[:,2])
print("\nFirst two rows and first 2 coloums:\n",arr2D[:2,:2])


First row: [10 20 30]

Second row: [40 50 60]

Third row: [70 80 90]

First coloum: [10 40 70]

Secomd coloum: [20 50 80]

Third coloum: [30 60 90]

First two rows and first 2 coloums:
 [[10 20]
 [40 50]]


In [154]:
# ========================================
# AXIS OPERATIONS (Critical for ML!)
# ========================================

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Matrix:\n", matrix)
print("\n")
print("Sum of entire matrix:", matrix.sum())
print("\nSum along axis=0 (column sums):", matrix.sum(axis=0))
print("Sum along axis=1 (row sums):", matrix.sum(axis=1))
print("\n" + "-"*50 + "\n")
print("Mean along axis=0:", matrix.mean(axis=0))
print("Mean along axis=1:", matrix.mean(axis=1))
print("\n" + "-"*50 + "\n")
print("Max along axis=0:", matrix.max(axis=0))
print("Max along axis=1:", matrix.max(axis=1))

Matrix:
 [[1 2 3]
 [4 5 6]]


Sum of entire matrix: 21

Sum along axis=0 (column sums): [5 7 9]
Sum along axis=1 (row sums): [ 6 15]

--------------------------------------------------

Mean along axis=0: [2.5 3.5 4.5]
Mean along axis=1: [2. 5.]

--------------------------------------------------

Max along axis=0: [4 5 6]
Max along axis=1: [3 6]


---

## 5️⃣ Mathematical Functions <a id="math"></a>

NumPy provides optimized mathematical functions:
- **Aggregations:** sum, mean, std, var, min, max
- **Element-wise:** sqrt, exp, log, sin, cos
- **Linear Algebra:** dot product, matrix multiplication

---

In [155]:
# ========================================
# STATISTICAL FUNCTIONS
# ========================================

data = np.array([85, 92, 78, 95, 88, 76, 90, 82])

print("Data:", data)
print("\n")
# Central tendency
print("Mean (average):", data.mean())
print("Median:", np.median(data))
print("\n")
# Spread
print("Standard Deviation:", data.std())
print("Variance:", data.var())
print("\n")
# Range
print("Min:", data.min())
print("Max:", data.max())
print("Range:", data.max() - data.min())
print("\n")
# Position
print("Index of min:", data.argmin())
print("Index of max:", data.argmax())
print("\n")
# Cumulative
print("Cumulative sum:", data.cumsum())

Data: [85 92 78 95 88 76 90 82]


Mean (average): 85.75
Median: 86.5


Standard Deviation: 6.299801584177076
Variance: 39.6875


Min: 76
Max: 95
Range: 19


Index of min: 5
Index of max: 3


Cumulative sum: [ 85 177 255 350 438 514 604 686]


In [156]:
# ========================================
# ELEMENT-WISE MATH FUNCTIONS
# ========================================

arr = np.array([1, 4, 9, 16, 25])

print("Original:", arr)
print("\nSquare Root:\n\n", np.sqrt(arr))
print("\nExponential:\n\n", np.exp(arr))
print("\nLog (natural):\n\n", np.log(arr))

print("\n" + "-"*50 + "\n")

# Trigonometry
angles = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(angles)  # Convert to radians

print("\nAngles (degrees):\n\n", angles)
print("\nSin:\n\n", np.sin(radians))
print("\nCos:\n\n", np.cos(radians))

Original: [ 1  4  9 16 25]

Square Root:

 [1. 2. 3. 4. 5.]

Exponential:

 [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Log (natural):

 [0.         1.38629436 2.19722458 2.77258872 3.21887582]

--------------------------------------------------


Angles (degrees):

 [ 0 30 45 60 90]

Sin:

 [0.         0.5        0.70710678 0.8660254  1.        ]

Cos:

 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [157]:
# ========================================
# DOT PRODUCT (Essential for ML!)
# ========================================

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Vector a:", a)
print("Vector b:", b)
print("Dot product:", dot_product)
print("\n" + "-"*50 + "\n")

# ========================================
# MATRIX MULTIPLICATION
# ========================================

A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
result1 = np.dot(A, B)
print("Matrix A:\n\n",A)
print("\nMatrix B:\n\n",B)
print("\nA x B:\n\n",result1)

Vector a: [1 2 3]
Vector b: [4 5 6]
Dot product: 32

--------------------------------------------------

Matrix A:

 [[1 2]
 [3 4]]

Matrix B:

 [[5 6]
 [7 8]]

A x B:

 [[19 22]
 [43 50]]


---

## 6️⃣ Boolean Indexing & Filtering <a id="boolean"></a>

**Boolean indexing** = filtering arrays based on conditions.  
This is POWERFUL for data cleaning and analysis!

---

In [158]:
# ========================================
# BOOLEAN INDEXING
# ========================================

scores = np.array([65, 72, 88, 95, 58, 91, 77, 82])
print("Scores:", scores)
print("\n")
above_80 = scores > 80
print("Scores > 80 (mask):", above_80)
print("Scores > 80 (values):", scores[above_80])
print("Total who Scores > 80 :", np.sum(scores > 80))
print("\n" + "-"*50 + "\n")

high_scores = (scores >= 85) & (scores <= 95)
print("Scores between 85-95:", scores[high_scores])
print("\n")
count = np.sum(scores > 80)  # True=1, False=0
print("Number of scores > 80:", count)
percent = (count / len(scores)) * 100
print(f"Percentage > 80: {percent:.1f}%")

Scores: [65 72 88 95 58 91 77 82]


Scores > 80 (mask): [False False  True  True False  True False  True]
Scores > 80 (values): [88 95 91 82]
Total who Scores > 80 : 4

--------------------------------------------------

Scores between 85-95: [88 95 91]


Number of scores > 80: 4
Percentage > 80: 50.0%


In [159]:
# ========================================
# MODIFYING BASED ON CONDITIONS
# ========================================

grades = np.array([55, 68, 72, 85, 92, 45, 78])
print("Original grades:", grades)

grades[grades < 60] += 5

print("After +5 bonus to <60:", grades)

print("\n" + "-"*50 + "\n")

data = np.array([75, 88, 95, 102, 85, 98])
print("Before cap:", data)

data[data > 90] = 90 
print("After cap at 90:", data)

Original grades: [55 68 72 85 92 45 78]
After +5 bonus to <60: [60 68 72 85 92 50 78]

--------------------------------------------------

Before cap: [ 75  88  95 102  85  98]
After cap at 90: [75 88 90 90 85 90]


---

## 7️⃣ Real-World Applications <a id="applications"></a>
---

In [160]:


subjects = ["Math", "Physics", "Chemistry", "English", "CS"]
scores = np.array([56, 32, 78, 95, 88])

print("\n" + "="*50)
print("STUDENT REPORT CARD")
print("="*50 + "\n")

for subject, score in zip(subjects, scores):
    print(f"{subject:12}: {score}")

print("\n" + "="*50 + "\n")

# Statistics
avg = scores.mean()

print(f"Average Marks: {avg:.2f}")
print(f"Highest Marks: {scores.max()} in {subjects[scores.argmax()]}")
print(f"Lowest Marks: {scores.min()} in {subjects[scores.argmin()]}")

# Grade calculation
if avg >= 90:
    grade = "A+"
elif avg >= 80:
    grade = "A"
elif avg >= 70:
    grade = "B"
elif avg >= 60:
    grade = "C"
elif avg >= 40:
    grade = "D"
else:
    grade = "Fail"

print("Grade:", grade)

# Weak subjects
weak_mask = scores < 70
print("Focus on:", np.array(subjects)[weak_mask])


STUDENT REPORT CARD

Math        : 56
Physics     : 32
Chemistry   : 78
English     : 95
CS          : 88


Average Marks: 69.80
Highest Marks: 95 in English
Lowest Marks: 32 in Physics
Grade: C
Focus on: ['Math' 'Physics']


In [161]:
# Store Sales Analyzer
# Scenario
# A store sells 4 products across 6 months.
# You need to analyze the business performance.

In [162]:
sales = np.array([
    [12000,13000,23000,17000,23000],
    [23000,12000,24000,34000,12000],
    [13000,12000,16000,19000,23000],
    [23000,34000,42000,28000,45000]
])
products = ["Laptop","Phone","Tablet","Accessories"]
months = ["Jan","Feb","Mar","Apr","May","Jun"]

print("Dataset:\n")
for i in range(len(products)):
    print(f"{products[i]}: {sales[i]}")
print("\n"+"="*50+"\n")
print("Total sales per product:\n")
for i in range(len(products)):
    total  = np.sum(sales[i])
    print(f"{products[i]} total sales: {total}")
print("\n"+"="*50+"\n")
print("Monthly revenue:\n")
for i in range(len(products)):
    total = np.sum(sales[i], axis=0)
    print(f"{months[i]}: {total}")
print("\n"+"="*50+"\n")
print("Best selling product:", products[sales.sum(axis=1).argmax()])
print("Least sold product:",products[sales.sum(axis=1).argmin()])
print("\n"+"="*50+"\n")
print("Best month for business: ",months[sales.sum(axis=0).argmax()])
print("Month with least sales: ",months[sales.sum(axis=0).argmin()])
print("\n"+"="*50+"\n")
print("Growth Analysis")
for i in range(len(products)):
    start = sales[i,0]
    end = sales[i,-1]
    growth = (end - start) / start * 100
    print(f"{products[i]} growth: {growth:.1f}%")
print("\n"+"="*50+"\n")
print("Average Monthly Sales:\n")
for i in range(len(products)):
    print(f"{products[i]} average: {np.mean(sales[i])}")
print("\n"+"="*50+"\n")
print("High Revenue Detection:")
rows, cols = np.where(sales > 30000)

for r, c in zip(rows, cols):
    print(f"{products[r]} in {months[c]}: {sales[r,c]}")

print("\n"+"="*50+"\n")
print("Business Summary: ")
total_revenue = sales.sum()
average_sale = sales.mean()
highest_sale = sales.max()
lowest_sale = sales.min()
print("Total revenue: ",total_revenue)
print("Average sale:",average_sale)
print("Highest sale:",highest_sale)
print("Lowest sales:",lowest_sale)

Dataset:

Laptop: [12000 13000 23000 17000 23000]
Phone: [23000 12000 24000 34000 12000]
Tablet: [13000 12000 16000 19000 23000]
Accessories: [23000 34000 42000 28000 45000]


Total sales per product:

Laptop total sales: 88000
Phone total sales: 105000
Tablet total sales: 83000
Accessories total sales: 172000


Monthly revenue:

Jan: 88000
Feb: 105000
Mar: 83000
Apr: 172000


Best selling product: Accessories
Least sold product: Tablet


Best month for business:  Mar
Month with least sales:  Jan


Growth Analysis
Laptop growth: 91.7%
Phone growth: -47.8%
Tablet growth: 76.9%
Accessories growth: 95.7%


Average Monthly Sales:

Laptop average: 17600.0
Phone average: 21000.0
Tablet average: 16600.0
Accessories average: 34400.0


High Revenue Detection:
Phone in Apr: 34000
Accessories in Feb: 34000
Accessories in Mar: 42000
Accessories in May: 45000


Business Summary: 
Total revenue:  448000
Average sale: 22400.0
Highest sale: 45000
Lowest sales: 12000


In [163]:
# Application 3
# Sensor Anomaly Detection System

# Scenario

# A machine has 5 sensors measuring temperature every hour.

# You need to analyze the data and detect abnormal readings.

In [164]:

sensors = ["S1","S2","S3","S4","S5"]
hours = ["H1","H2","H3","H4","H5","H5","H6"]
temps = np.array([
    [45, 47, 49, 50, 52, 54],
    [60, 62, 61, 65, 67, 70],
    [55, 58, 92, 60, 63, 65],
    [40, 42, 44, 46, 48, 50],
    [70, 75, 78, 82, 85, 88]
])

In [165]:
print("Display sensor readings:")
for sensor,data in zip(sensors,temps):
    print(f"{sensor}: {data}")

Display sensor readings:
S1: [45 47 49 50 52 54]
S2: [60 62 61 65 67 70]
S3: [55 58 92 60 63 65]
S4: [40 42 44 46 48 50]
S5: [70 75 78 82 85 88]


In [166]:
print("Average temperature per sensor:")
avg = temps.mean(axis=1)
for sensor,data in zip(sensors,avg):
    print(f"{sensor} = {data:.2f}")

Average temperature per sensor:
S1 = 49.50
S2 = 64.17
S3 = 65.50
S4 = 45.00
S5 = 79.67


In [167]:
print("Highest temperature recorded:")
max_temp = temps.max()

rows, cols = np.where(temps == max_temp)

print("Highest temperature:", max_temp)
print("Sensor:", sensors[rows[0]])
print("Hour:", hours[cols[0]])

Highest temperature recorded:
Highest temperature: 92
Sensor: S3
Hour: H3


In [168]:
print("Average temperature per sensor")
avg_temp = temps.mean(axis=1)
print("\nAverage Temperature per sensor")
for sensor,avg in zip(sensors,avg_temp):
    print(f"{sensor} average temperature: {avg:.2f}")

Average temperature per sensor

Average Temperature per sensor
S1 average temperature: 49.50
S2 average temperature: 64.17
S3 average temperature: 65.50
S4 average temperature: 45.00
S5 average temperature: 79.67


In [169]:
# Sensor stability check
fluctuation = temps.std(axis=1)
print("Sensor Stability (Standard deviation)")
for sensor,value in zip(sensors,fluctuation):
    print(f"{sensor} fluctuation: {value:.2f}")

Sensor Stability (Standard deviation)
S1 fluctuation: 2.99
S2 fluctuation: 3.53
S3 fluctuation: 12.28
S4 fluctuation: 3.42
S5 fluctuation: 6.07


In [170]:
# MOst stable sensor
stable_index = fluctuation.argmin()
print("Most Stable sensor: ",sensors[stable_index])

Most Stable sensor:  S1


In [171]:
# Detect overheating sensors
rows,cols = np.where(temps>80)
print("Overheating Sensors Detected")
for r,c in zip(rows,cols):
    print(f"{sensors[r]} at {hours[c]} : {temps[r,c]} C")

Overheating Sensors Detected
S3 at H3 : 92 C
S5 at H4 : 82 C
S5 at H5 : 85 C
S5 at H5 : 88 C


In [172]:
#Hours with highest avg temp
hour_avg = temps.mean(axis=0)
hottest_hour_index = hour_avg.argmax()
print("Hour with highest average temp")
print("Hour:",hours[hottest_hour_index])
print("Average temperature:",hour_avg[hottest_hour_index])

Hour with highest average temp
Hour: H5
Average temperature: 65.4


In [173]:
#Temperature summary
print("Temperature summary")
print("Average temperature: ",temps.mean())
print("highest temperature:",temps.max())
print("lowest temperature:",temps.min())

Temperature summary
Average temperature:  60.766666666666666
highest temperature: 92
lowest temperature: 40


In [174]:
#Safety alert system
if np.any(temps>90):
    print("CRITICAL ALERT: MACHINE OVERHEATING DETECTED")
else:
    print("System operating normally")

CRITICAL ALERT: MACHINE OVERHEATING DETECTED


## 🎯 Key Takeaways

**What I Learned:**
- NumPy arrays are 10-50x faster than Python lists
- axis=0 = down columns, axis=1 = across rows (critical for ML)
- Boolean indexing for filtering data
- Real-world applications: sensor monitoring, data analysis

**Next Steps:**
- Pandas (data manipulation)
- Matplotlib (visualization)  
- Scikit-learn (machine learning)

**Time Invested:** 3+ hours  
**Status:** ✅ Complete  

---

*March 2026 | Tuvya Algotar | NMIMS AI & DS*